
server:
  port: 9999
spring:
  profiles:
    active: dev
  application:
    name: gateway-dynamic-route
  redis:
    host: 120.78.215.14
    port: 6379
    password: YiZheng123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 服务名小写
          lower-case-service-id: true

# 注册中心
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://zy:zy123@localhost:10025/eureka/




