

server:
  port: 8088
spring:
  application:
    name: order-service-prometheus
  cloud:
    consul:
      discovery:
        enabled: true
        register: true
        heartbeat:
          enabled: true
          ttl-unit: s
          ttl-value: 30
        prefer-ip-address: true
        tags: prometheus
      host: localhost
      port: 8500
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application : ${spring.application.name}

